// LOCALHOST

### GET all
GET http://localhost:8080/data
### GET by ID
GET http://localhost:8080/data/data_id
### POST
POST http://localhost:8080/data HTTP/1.1
content-type: application/json

{
    "unitName": "Medium scout car",
    "unitCost": "30 points",
    "unitType": "vehicle",
    "upgrades": "none",
    "unitSize": "medium"
}
### PUT by ID
PUT http://localhost:8080/data/data_id HTTP/1.1
content-type: application/json

{
    "unitName": "Medium scout car",
    "unitCost": "35 points",
    "unitType": "vehicle",
    "upgrades": "long-range-radio",
    "unitSize": "medium"
}
### DELETE by ID
DELETE http://localhost:8080/data/data_id HTTP/1.1

// RENDER

### GET all
GET https://cse341-lesson5-2chr.onrender.com/data
### GET by ID
GET https://cse341-lesson5-2chr.onrender.com/data/data_id HTTP/1.1
### POST
POST https://cse341-lesson5-2chr.onrender.com/data HTTP/1.1
content-type: application/json

{
    "unitName": "Medium scout car",
    "unitCost": "30 points",
    "unitType": "vehicle",
    "upgrades": "none",
    "unitSize": "medium"
}
### PUT by ID
PUT https://cse341-lesson5-2chr.onrender.com/data/6832aa5185260994665ade33 HTTP/1.1
content-type: application/json

{
    "unitName": "Medium scout car",
    "unitCost": "35 points",
    "unitType": "vehicle",
    "upgrades": "long-range-radio",
    "unitSize": "medium"
}
### DELETE by ID
DELETE https://cse341-lesson5-2chr.onrender.com/data/6832aa5185260994665ade33 HTTP/1.1

// Lesson 5 Swagger API
###
http://localhost:8080/api-docs
###
https://cse341-lesson5-2chr.onrender.com/api-docs